name: Cloudflare Purge Cache

on: [ page_build ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cloudflare Purge Cache
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_AUTH_EMAIL }}" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_AUTH_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything": true}'
