name: Update blog posts to README

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  watch:
    types: [started]

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://baoshuo.blog/atom.xml
          readme-section: posts
